### PR TITLE
Fix issue related to serialization of strings containing whitespace characters

### LINKED ISSUE #950: WW does not deserialize strings with newline characters properly with Koalas dataframes
If I have a string column in a dataframe that contains newline characters and serialize and deserialize the dataframe, the deserialized dataframe is not recreated properly.

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
>>> import pandas as pd
>>> import databricks.koalas as ks
>>> import woodwork as ww
>>> from woodwork.deserialize import read_woodwork_table
>>> df = pd.DataFrame({
...     'id': [0, 1, 2, 3],
...     'comments': [
...         '\ncomment1\n',
...         '\nleading newline',
...         'trailing\n',
...         'in the \n middle'
...     ]
... })
>>> ks_df = ks.from_pandas(df)
>>> ks_df.ww.init()
>>> ks_df.ww.to_disk('.')                                                       
>>> new_df = read_woodwork_table('.')
>>> new_df
    id         comments
0  3.0          in the 
1  NaN             <NA>
2  1.0  leading newline
3  2.0         trailing
4  0.0         comment1
```

### PR DESCRIPTION
**Pull request by thehomebrewnerd**
- Fix issue related to serialization of strings containing whitespace characters
- Closes #950 

Serialization and deserialization of Koalas dataframes containing leading and trailing whitespace characters and/or newline characters anywhere in the string was not working correctly. This PR updates the default spark settings used so that whitespace and newline characters are handled correctly. Also, the previous implementation was not passing any additional user specified kwargs to the underlying to_csv methods. This PR also contains updates to allow users to pass additional kwargs if needed.

### CODE REVIEW

**Comment by thehomebrewnerd** [comment]
I tested Featuretools serialization with this branch and it fixes the issues I was seeing with deserializing the `log` dataframe which contains newline characters.

**Comment by rwedge** [comment]
branch is out-of-date but what's here looks good

**Comment by thehomebrewnerd** [comment]
> branch is out-of-date but what's here looks good

@rwedge Updated branch

**Review by rwedge — APPROVED** [review]
Looks good

**Pull request merged**
